### ISSUE TITLE
slideshows

### ISSUE THREAD

**Issue by velosoof** [pixelman/jowan#89]
bij de nieuwe slideshows (fotoalbums) die ik nu gemaakt heb begint de reeks steeds met het laatste beeld ipv met het eerste. na dat laatste beeld komt dan wel het eerste beeld 
beke raar

**Comment by pixelman** [comment]
de slideshow is buggy, krijg hem niet goed, ik heb ondertussen ook vernomen dat ze de ontwikkeling ervan stopgezet hebben. Ik ben een andere nieuwe aan het integreren. Die beter en vlotter werk.

**Comment by pixelman** [comment]
er is een nieuwe gallerymodule geintegreerd.
er zijn nu 2 opties qua slideshow stijl:
- een image stream, een soort van doorlopende band met beelden na elkaar
- een klassieke beeld per beeld slideshow

Je kan dit instellen per slideshow via een schuifknop
