### ISSUE TITLE
uitlijning van items in de kijker: centreren indien weinig items

### ISSUE THREAD

**Issue by pixelman** [pixelman/jowan#98]
hier ga ik niets beloven, ik gebruik een plugin (http://isotope.metafizzy.co) voor het berekenen van de blokjes. Dat is bestaande software die je kan integreren.
Dat vult gaten op maar start van links. Bij het ontwerpen had ik dat ook zo in gedachten maar heb dit er nog niet uitgekregen. Maar zal zien of er ondertussen al een mogelijke parameter bestaat om gecentreerd uit te lijnen.

**Comment by pixelman** [comment]
heb eens gezien en er is een mogelijke oplossing via een nieuwe methode. Hier is wel wat werk aan vrees ik. http://w3bits.com/demo/responsive-css-masonry/
verschil is dat bij de huidige site we een javascript gebruiken, waar het bij de nieuwe code zonder script is. Vraag is of dit ook werkt pc IE. Moet ik uitproberen

**Comment by pixelman** [comment]
blijkbaar is de volgorde vanb de items al een issue…

**Comment by velosoof** [comment]
je ziet maar of het doenbaar is. dacht dat het maar op een knopje 'centreren' duwen was.

**Comment by pixelman** [comment]
dit is dus niet haalbaar met de huidige module.
